name: Spell-check

on:
  workflow_dispatch:
  push:
    paths:
      - "**.md"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check spelling
        uses: streetsidesoftware/cspell-action@v5
        with:
          files: "**/*.mdx"
          verbose: true